### ISSUE TITLE
segfault after long runtime

### ISSUE THREAD

**Issue by cipig** [KomodoPlatform/atomicDEX-Pro#104]
When i let AtomicDEX-Pro run for a longer period of time (eg 24h), it segfaults.
So i restarted it with gdb and collected this backtrace:
```
(gdb) backtrace
#0  0x00007ffff6abd7a4 in QV4::MarkStack::push (this=0x7fffffffaf10, m=0x7fff69a68220) at ../../include/QtQml/5.14.2/QtQml/private/../../../../../src/qml/memory/qv4mmdefs_p.h:280
#1  QV4::Heap::Base::mark (markStack=0x7fffffffaf10, this=0x7fff69a68220) at ../../include/QtQml/5.14.2/QtQml/private/../../../../../src/qml/memory/qv4heap_p.h:192
#2  QV4::Value::mark (markStack=0x7fffffffaf10, this=<optimized out>) at jsruntime/qv4value_p.h:362
#3  QV4::WeakValue::markOnce (this=<optimized out>, markStack=0x7fffffffaf10) at jsruntime/qv4persistent.cpp:415
#4  0x00007ffff6b2c2a0 in markChildQObjectsRecursively (parent=parent@entry=0x7fffffffdc98, markStack=markStack@entry=0x7fffffffaf10) at jsruntime/qv4qobjectwrapper.cpp:1134
#5  0x00007ffff6b2c34b in QV4::Heap::QObjectWrapper::markObjects (that=0x7fffece2ba40, markStack=0x7fffffffaf10) at jsruntime/qv4qobjectwrapper.cpp:1153
#6  0x00007ffff6a4441f in QV4::MarkStack::drain (this=this@entry=0x7fffffffaf10) at memory/qv4mm.cpp:863
#7  0x00007ffff6abd142 in QV4::PersistentValueStorage::mark (this=<optimized out>, markStack=markStack@entry=0x7fffffffaf10) at jsruntime/qv4persistent.cpp:243
#8  0x00007ffff6a4479d in QV4::MemoryManager::collectRoots (this=this@entry=0xfc2820, markStack=markStack@entry=0x7fffffffaf10) at memory/qv4mm.cpp:876
#9  0x00007ffff6a44989 in QV4::MemoryManager::mark (this=this@entry=0xfc2820) at memory/qv4mm.cpp:917
#10 0x00007ffff6a4675b in QV4::MemoryManager::runGC (this=this@entry=0xfc2820) at memory/qv4mm.cpp:1052
#11 0x00007ffff6a48ac8 in QV4::MemoryManager::allocate (size=32, allocator=0xfc2830, this=0xfc2820) at ../../include/QtQml/5.14.2/QtQml/private/../../../../../src/qml/memory/qv4mm_p.h:307
#12 QV4::MemoryManager::allocString (this=this@entry=0xfc2820, unmanagedSize=<optimized out>) at memory/qv4mm.cpp:787
#13 0x00007ffff6aa7711 in QV4::MemoryManager::allocWithStringData<QV4::String, QString> (arg1=..., unmanagedSize=<optimized out>, this=0xfc2820) at ../../include/QtQml/5.14.2/QtQml/private/../../../../../src/qml/memory/qv4mm_p.h:217
#14 QV4::ExecutionEngine::newString (this=this@entry=0xfc6a90, s=...) at jsruntime/qv4engine.cpp:890
#15 0x00007ffff6b30682 in loadProperty (v4=0xfc6a90, object=0x7fffffffdc98, property=...) at jsruntime/qv4qobjectwrapper.cpp:157
#16 0x00007fffd9404653 in ?? ()
#17 0x0000000000000000 in ?? ()
```

seems to happen in `process_fees` loop... this is from console
```
16:26:20.425 [fees thread     ]     atomic.dex.mm2.cpp:601   INFO| .   { process_fees
...
...
...
16:26:20.468 [orderbook thread] atomic.dex.mm2.api.cpp:605   INFO| .   .   resp: {"result":{"amount":"0.00021125","coin":"BTC"}}
16:26:20.561 [fees thread     ] atomic.dex.mm2.api.cpp:605   INFO| .   .   resp: {"result":{"amount":"0.00001039","coin":"LTC"}}
```
then it segfaults

**Comment by Milerius** [comment]
According to your backtrace you just find a QT bug in their JavaScript engine, it's seems they have a memory leak on Linux.

**Comment by cipig** [comment]
Indeed, the memory usage increases over time. I close the issue, since not related to atomicDEX-Pro.
